export const string = {
  redux_example: 'Redux Counter Example',
  hooks_example: 'Hooks Example',
  redux_saga_example: 'Redux-Saga Example',
  use_imperative_handle_example: 'useImperativeHandle Example',
  increment: 'Increment',
  decrement: 'Decrement',
  context_hook: 'ContextHook',
  reducer_hook: 'ReducerHook',
  use_ref_hook: 'UseRefHook',
  memo_hook: 'MemoHook',
  imperative_handle: 'ImperativeHandle',
  login: 'Login',
  login_account: 'Please login to your account',
  register: 'Register',
  dont_have_account: "Don't have an account? ",
  register_account: 'Please enter details to register',
  have_account: 'Already have an account? ',
  connection_lost: 'Connection Lost!',
  no_internet_msg:
    'No internet connection. Make sure that Wi-Fi or mobile data is turned on, then try again.',
  forgot_password: 'Forgot Password?',
  logout: 'Logout',
};
