export default {
  NETWORK_INFO: 'NETWORK_INFO',

  INCREASE_COUNT: 'INCREASE_COUNT',
  DECREASE_COUNT: 'DECREASE_COUNT',
  RESET_COUNT: 'RESET_COUNT',

  GET_POSTS: 'GET_POSTS',
  GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
  GET_POSTS_FAILED: 'GET_POSTS_FAILED',
  RESET_POST: 'RESET_POST',

  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
};
